export const copy = {
  brand: 'Norte',
  productName: 'JoeXavi Dev Hours',
  productDescription:
    'Senior full-stack pairing time. Ship features, untangle architecture, and leave with clearer next steps.',
  usdPrice: 'USD 20 / hour',
  copHelper: 'COP 50.000 billed per hour',
  hoursLabel: 'Hours',
  hoursAvailable: (n: number) => `${n} hours available`,
  payCta: 'Pay with credit card',
  soldOut: 'Sold out',
  cardSection: 'Card',
  deliverySection: 'Delivery',
  testCardsHelper: 'Test cards only',
  continueToSummary: 'Continue to summary',
  cardNumber: 'Card number',
  expiry: 'Expiry',
  cvc: 'CVC',
  cardholder: 'Name on card',
  email: 'Email',
  fullName: 'Full name',
  phone: 'Phone',
  legalId: 'ID number',
  legalIdType: 'ID type',
  addressLine1: 'Address line 1',
  addressLine2: 'Address line 2 (optional)',
  city: 'City',
  region: 'Region',
  summaryTitle: 'Order summary',
  hoursSubtotal: 'Hours subtotal',
  baseFee: 'Base fee',
  deliveryFee: 'Delivery fee',
  total: 'Total',
  usdEquivalent: (usd: string) => `≈ USD ${usd}`,
  acceptTerms: 'I accept the end-user policy',
  acceptData: 'I authorize personal data processing',
  payTotal: (amount: string) => `Pay ${amount}`,
  pendingTitle: 'Processing payment',
  pendingHint: 'This usually takes a few seconds',
  checkAgain: 'Check again',
  approvedTitle: 'Payment approved',
  approvedBody: (n: number) => `${n} pairing hours are booked.`,
  declinedTitle: 'Payment declined',
  declinedBody: 'Nothing was charged. Those hours are available again.',
  tryAnotherCard: 'Try another card',
  backToStore: 'Back to store',
  reference: 'Reference',
  receipt: 'Receipt',
  outOfStock: (n: number) => `Only ${n} hours left`,
  networkError: 'Something went wrong. Check your connection and try again.',
  tokenizationError: 'We could not tokenize your card. Check the details and try again.',
  acceptBoth: 'You must accept both policies to continue',
  errors: {
    cardNumber: 'Enter a valid card number',
    cardBrand: 'Only Visa and Mastercard are accepted',
    expiry: 'Enter a valid expiry date',
    cvc: 'Enter the 3-digit code',
    cardholder: 'Enter the name on the card',
    email: 'Enter a valid email',
    phone: 'Enter a valid phone number',
    addressLine1: 'Enter your address',
    required: 'Required',
    hours: (available: number) => `Choose between 1 and ${available} hours`,
  },
} as const;
